# Generated by Django 5.1.1 on 2024-09-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='has_voted',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='name',
        ),
        migrations.AddField(
            model_name='voter',
            name='voter_id',
            field=models.CharField(default='default_voter_id', max_length=8, unique=True),
        ),
    ]
