# Generated by Django 5.1.1 on 2024-09-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_remove_voter_has_voted_remove_voter_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voter_name',
            field=models.CharField(default='default_voter_name', max_length=120),
        ),
    ]
